package util.text;

import snake2d.util.datatypes.DIR;

public class Dic {

	
	public static CharSequence empty = "";
	public static CharSequence ¤¤Accept = "¤Accept";
	public static CharSequence ¤¤Access = "¤Access";
	public static CharSequence ¤¤AccidentRate = "¤Accident Rate";
	public static CharSequence ¤¤AccidentRateD = "¤The rough chance of someone getting injured or killed in an accident in any of your rooms yearly.";
	public static CharSequence ¤¤Activate = "¤Activate";
	public static CharSequence ¤¤Activated = "¤Activated";
	public static CharSequence ¤¤Addative = "¤Additive";
	public static CharSequence ¤¤Admin = "¤Admin";
	public static CharSequence ¤¤AdultAge = "¤Adult at Day:";
	public static CharSequence ¤¤Age = "¤Age:";
	public static CharSequence ¤¤Alert = "¤Alert";
	public static CharSequence ¤¤All = "¤All";
	public static CharSequence ¤¤Allocated = "¤Allocated";
	public static CharSequence ¤¤Ammunition = "¤Ammunition";
	public static CharSequence ¤¤Amount = "¤Amount";
	public static CharSequence ¤¤Animals = "¤Animals";
	
	public static CharSequence ¤¤Area = "¤Area";
	public static CharSequence ¤¤Armies = "¤Armies";
	public static CharSequence ¤¤Army = "¤Army";
	public static CharSequence ¤¤Artillery = "¤Artillery";
	public static CharSequence ¤¤Assault = "¤Assault";
	public static CharSequence ¤¤AtWar = "¤At War";
	public static CharSequence ¤¤Attack = "¤Attack";
	public static CharSequence ¤¤Attacking = "¤Attacking";
	
	public static CharSequence ¤¤Available = "¤Available";
	public static CharSequence ¤¤Baby = "¤Infant";
	public static CharSequence ¤¤Babies = "¤Infants";
	public static CharSequence ¤¤Back = "¤Back";
	public static CharSequence ¤¤Balance = "¤Balance";
	public static CharSequence ¤¤Banner = "¤Banner";
	public static CharSequence ¤¤Base = "¤Base";
	public static CharSequence ¤¤BaseValue = "¤Base Value";
	public static CharSequence ¤¤Battle = "¤Battle";
	public static CharSequence ¤¤BattleOf = "¤Battle of {0}";
	public static CharSequence ¤¤Besiege = "¤Besiege";
	public static CharSequence ¤¤Broken = "¤Broken";
	public static CharSequence ¤¤Besieging = "¤Besieging";
	public static CharSequence ¤¤BesiegingSomething = "¤Besieging {0}";
	public static CharSequence ¤¤Biome = "¤Biome";
	public static CharSequence ¤¤Boosts = "¤Boosts";
	public static CharSequence ¤¤Bought = "¤Bought";
	public static CharSequence ¤¤BoundFor = "¤Bound For {0}";
	public static CharSequence ¤¤Buildings = "¤Buildings";
	public static CharSequence ¤¤Buy = "¤Buy";
	public static CharSequence ¤¤Buyers = "¤Buyers";
	public static CharSequence ¤¤Campaigning = "¤Campaigning";
	public static CharSequence ¤¤CampaigningD = "¤Soldiers that are out campaigning.";
	public static CharSequence ¤¤CExitToMenu = "¤Exit to Menu";
	public static CharSequence ¤¤CDone = "¤Good, you have completed the current task. Now continue with:";
	public static CharSequence ¤¤Campaign = "¤Scenario";
	public static CharSequence ¤¤Capacity = "¤Capacity";
	public static CharSequence ¤¤Capitol = "¤Capital";
	public static CharSequence ¤¤CapitolYou = "¤Your Capital";
	public static CharSequence ¤¤CaptivesD = "¤Captives from the battle. You can decide how many you want to accept into your city as prisoners. The rest will be disposed. Take heed that stockades are needed as a first step to process these captives.";
	public static CharSequence ¤¤Caravan = "¤Caravan";
	public static CharSequence ¤¤Casualties = "¤Casualties";
	public static CharSequence ¤¤Civics = "Civics";
	public static CharSequence ¤¤Clear = "¤Clear";
	public static CharSequence ¤¤Close = "¤Close";
	public static CharSequence ¤¤Conscriptable = "¤Conscriptable";
	public static CharSequence ¤¤Conscripts = "¤Conscripts";
	public static CharSequence ¤¤ConscriptsD = "¤Conscripts are the population available to draft into armies, minus the ones already drafted. The max amount is determined by your regions, and with time, your actual conscripts will increase towards this target. If no fresh conscripts exist no new divisions can be trained and existing ones will not replenish.";
	public static CharSequence ¤¤Consumed = "Consumed";
	public static CharSequence ¤¤ConsumptionRate = "¤Consumption Rate";
	public static CharSequence ¤¤Copy = "¤Copy";
	public static CharSequence ¤¤Cost = "¤Cost";
	public static CharSequence ¤¤Count = "¤Count";
	public static CharSequence ¤¤Court = "Court";
	public static CharSequence ¤¤Create = "Create";
	public static CharSequence ¤¤Crime = "¤Crime";
	public static CharSequence ¤¤Curr = "¤Denari";
	public static CharSequence ¤¤Current = "¤Current";
	public static CharSequence ¤¤Currs = "¤Denari";
	public static CharSequence ¤¤CreditScore = "¤Purchasing Power";
	public static CharSequence ¤¤CreditScoreD = "¤When a faction spends money on imports, its purchasing power will drop, leading to prices dropping overall. The opposite is also true for money earned through exports";
	public static CharSequence ¤¤Deactivate = "¤Deactivate";
	public static CharSequence ¤¤Deactivated = "¤Deactivated";
	public static CharSequence ¤¤DeclareWar = "¤Declare War";
	public static CharSequence ¤¤Decline = "¤Decline";
	
	public static CharSequence ¤¤Defences = "¤Defenses";
	public static CharSequence ¤¤DefencesD = "¤Defenses are the product of your garrison and fortifications and this power can only be used in defence. When an army besieges a region, the garrison will decrease with time.";
	
	public static CharSequence ¤¤Defeat = "Defeat";
	public static CharSequence ¤¤Deaths = "Deaths";
	public static CharSequence ¤¤Degrade = "¤Degrade";
	public static CharSequence ¤¤DegradeDesc = "¤Most rooms and roads require maintenance provided by a janitor. If not provided, they will degrade and function poorly. Some maintenance requires materials.";
	public static CharSequence ¤¤Disease = "¤Disease";
	public static CharSequence ¤¤Deployable = "¤Deployable";
	public static CharSequence ¤¤Destination = "¤Destination";
	public static CharSequence ¤¤Diplomacy = "¤Diplomacy";
	public static CharSequence ¤¤Disband = "¤Disband";
	public static CharSequence ¤¤Distance = "¤Distance";
	public static CharSequence ¤¤Distant = "¤Distant Faction";
	public static CharSequence ¤¤FactionBorder = "¤Bordering Faction";
	public static CharSequence ¤¤Division = "¤Division";
	public static CharSequence ¤¤Drinkable = "¤Drinkable";
	public static CharSequence ¤¤Earnings = "¤Earnings";
	public static CharSequence ¤¤Edible = "¤Edible";
	public static CharSequence ¤¤Edit = "Edit";
	public static CharSequence ¤¤Effects = "¤Effects";
	public static CharSequence ¤¤Efficiency = "¤Efficiency";
	public static CharSequence ¤¤Emits = "¤Emits";
	public static CharSequence ¤¤Employees = "¤Employees";
	public static CharSequence ¤¤Employment = "¤Employment";
	public static CharSequence ¤¤Encyclopedia = "¤Encyclopedia";
	public static CharSequence ¤¤Enemies = "¤Enemies";
	public static CharSequence ¤¤Enemy = "¤Enemy";

	public static CharSequence ¤¤Equipment = "¤Equipment";
	public static CharSequence ¤¤Equipped = "¤Equipped";
	public static CharSequence ¤¤Event = "¤Event";
	public static CharSequence ¤¤Expenses = "¤Expenses";
	public static CharSequence ¤¤Experience = "¤Experience";
	public static CharSequence ¤¤Exporting = "¤Exporting";
	public static CharSequence ¤¤Faction = "¤Faction";
	public static CharSequence ¤¤Factions = "¤Factions";
	public static CharSequence ¤¤Factors = "¤Factors";
	public static CharSequence ¤¤Favourite = "¤Favourite";
	public static CharSequence ¤¤Fertility = "¤Fertility";
	public static CharSequence ¤¤FertilityD = "¤Fertility increases farm, pasture, and orchard output and allows for more wild crops to grow.";
	public static CharSequence ¤¤Filter = "¤Filter";
	public static CharSequence ¤¤Food = "¤Food";
	public static CharSequence ¤¤ForSale = "¤For Sale";
	public static CharSequence ¤¤Formation = "¤Formation";
	public static CharSequence ¤¤Fort = "¤Fortifications";
	public static CharSequence ¤¤FortD = "¤Fortifications give a huge boost to the defence of the settlement. It can make a direct assault impossible until the defenders are tired out and starved.";
	public static CharSequence ¤¤Fortifications = "¤Fortifications";
	public static CharSequence ¤¤Fortified = "¤Fortified";
	public static CharSequence ¤¤Fortifying = "¤Fortifying";
	public static CharSequence ¤¤Free = "¤Free";
	public static CharSequence ¤¤From = "From";
	public static CharSequence ¤¤Garrison = "¤Garrison";
	public static CharSequence ¤¤GarrisonD = "¤Garrisons will prolong an enemy siege and provide more attrition to enemies located in the region.";
	public static CharSequence ¤¤Generate = "¤Generate";
	public static CharSequence ¤¤Generating = "¤Generating";
	public static CharSequence ¤¤Growth = "¤Growth";
	public static CharSequence ¤¤Happiness = "¤Happiness";
	public static CharSequence ¤¤Health = "¤Health";
	public static CharSequence ¤¤High = "¤High";
	public static CharSequence ¤¤Home = "¤Home";
	public static CharSequence ¤¤HomeLess = "¤Homeless";
	public static CharSequence ¤¤Housing = "¤Housing";
	public static CharSequence ¤¤ImportLevel = "¤Import Level";
	public static CharSequence ¤¤Importable = "¤Importable";
	public static CharSequence ¤¤Inbound = "¤Inbound";
	public static CharSequence ¤¤Increase = "¤Increase";
	public static CharSequence ¤¤Info = "¤Info";
	public static CharSequence ¤¤InitialCost = "¤Initial Cost";
	public static CharSequence ¤¤Intercept = "¤Intercept";
	public static CharSequence ¤¤Intercepting = "¤Intercepting {0}";
	public static CharSequence ¤¤Isolation = "¤Insulation";
	public static CharSequence ¤¤Law = "¤Law";
	public static CharSequence ¤¤Less = "¤Less";
	public static CharSequence ¤¤Level = "¤Level";
	public static CharSequence ¤¤List = "¤List";
	public static CharSequence ¤¤Locked = "Locked";
	public static CharSequence ¤¤Losses = "¤Losses";
	public static CharSequence ¤¤Low = "¤Low";
	public static CharSequence ¤¤Maintenance = "Maintenance";
	public static CharSequence ¤¤MarchingTo = "¤Marching To {0}";
	public static CharSequence ¤¤Max = "¤Max";
	public static CharSequence ¤¤Menu = "¤Menu";
	public static CharSequence ¤¤Mercenaries = "¤Mercenaries";
	public static CharSequence ¤¤Messages = "¤Messages";
	public static CharSequence ¤¤Minerals = "¤Minerals";
	public static CharSequence ¤¤Minimum = "¤Minimum";
	public static CharSequence ¤¤Misc = "¤Misc.";
	public static CharSequence ¤¤Missing = "Missing";
	public static CharSequence ¤¤Modifiers = "¤Modifiers";
	public static CharSequence ¤¤Morale = "¤Morale";
	public static CharSequence ¤¤MoraleD = "¤Morale determines how long your troops will stand their ground for. Each division has an individual morale, that is also affected by a global one.";
	public static CharSequence ¤¤More = "¤More";
	public static CharSequence ¤¤MouseWheelAdd = "¤ + Mousewheel";
	public static CharSequence ¤¤Move = "¤Move Army. Moving armies do not replenish or muster new men.";
	public static CharSequence ¤¤MoveCant = "¤Army can't move when there are no soldiers.";
	public static CharSequence ¤¤Moving = "¤Moving";
	public static CharSequence ¤¤Mods = "Mods";
	public static CharSequence ¤¤Multipliers = "¤Multipliers";
	public static CharSequence ¤¤MustBeOwnRegion = "¤Must be in a controlled region";
	public static CharSequence ¤¤Muster = "¤Muster";

	public static CharSequence ¤¤Musterd = "¤Mustered";
	public static CharSequence ¤¤Needed = "¤Needed";
	public static CharSequence ¤¤Neighbours = "¤Neighbours";
	public static CharSequence ¤¤Net = "¤Net";
	public static CharSequence ¤¤NetWorth = "¤Net Worth";
	public static CharSequence ¤¤Neutral = "¤Neutral";
	public static CharSequence ¤¤Next = "¤Next";
	public static CharSequence ¤¤No = "¤No";
	public static CharSequence ¤¤Ruler = "¤Ruler";
	public static CharSequence ¤¤NoRuler = "¤Free Lands";
	public static CharSequence ¤¤None = "¤None";
	public static CharSequence ¤¤OK = "¤OK";
	public static CharSequence ¤¤OPTIONS = "¤OPTIONS";
	public static CharSequence ¤¤Occupation = "¤Occupation";
	public static CharSequence ¤¤Occurrence = "¤Occurrence";
	public static CharSequence ¤¤Oddjobber = "¤Oddjobber";
	public static CharSequence ¤¤Oddjobbers = "¤Oddjobbers";
	public static CharSequence ¤¤Rivalry = "Rivalry";
	public static CharSequence ¤¤RivalryD = "Your net worth against the faction's net worth determines rivalry, that dictates the aggression the faction will show towards you.";
	
	public static CharSequence ¤¤Organization = "¤Organisation";
	public static CharSequence ¤¤Outbound = "¤Outbound";
	public static CharSequence ¤¤Overlay = "¤Overlay";
	public static CharSequence ¤¤Overlays = "¤Overlays";
	public static CharSequence ¤¤Population = "¤Population";
	public static CharSequence ¤¤PlayTime = "¤PlayTime:";
	public static CharSequence ¤¤Power = "¤Power";
	public static CharSequence ¤¤Previous = "¤Previous";
	public static CharSequence ¤¤Price = "¤Price";
	public static CharSequence ¤¤PriceCap = "¤Price Cap";
	public static CharSequence ¤¤Priority = "¤Priority";
	public static CharSequence ¤¤Problem = "¤Problem";
	public static CharSequence ¤¤Produced = "¤Produced";
	public static CharSequence ¤¤Production = "¤Production";
	public static CharSequence ¤¤ProductionRate = "¤Production Rate";
	public static CharSequence ¤¤Progress = "¤Progress";
	public static CharSequence ¤¤Projectiles = "¤Projectiles";
	public static CharSequence ¤¤Properites = "¤Properties";
	public static CharSequence ¤¤Prospect = "¤Prospect";
	public static CharSequence ¤¤Punishment = "¤Punishment";
	public static CharSequence ¤¤Quality = "¤Quality";
	public static CharSequence ¤¤Raiding = "¤Raiding";
	public static CharSequence ¤¤Raiders = "¤Raiders";
	public static CharSequence ¤¤RaidingD = "¤When raiding an army will plunder the region they are in, gaining resources and slaves. Of course, it will not be appreciated by the owner.";
	public static CharSequence ¤¤Rarity = "¤Rarity";
	public static CharSequence ¤¤Rate = "¤Rate";
	public static CharSequence ¤¤ReadyFire = "¤Ready to Fire.";
	public static CharSequence ¤¤Realm = "Realm";
	public static CharSequence ¤¤Reassign = "¤Reassign";
	public static CharSequence ¤¤Rebels = "¤Rebels";
	public static CharSequence ¤¤Recruit = "¤Recruit";
	public static CharSequence ¤¤Recruits = "¤Recruits";
	public static CharSequence ¤¤Region = "Region";
	public static CharSequence ¤¤RegionDesc = "¤The world is made up of regions. Regions have people living in them, whose lives you can control if you manage to capture it. A region has an urban center, that can either be a town of a faction capital. You upgrade regions with administration points.";
	public static CharSequence ¤¤Regional = "Regional {0}";
	public static CharSequence ¤¤Regions = "¤Regions";
	public static CharSequence ¤¤Religion = "Religion";
	public static CharSequence ¤¤Reloading = "¤Reloading";
	public static CharSequence ¤¤ReloadingXX = "¤Unavailable. Reloading, ({0} seconds remaining)";
	public static CharSequence ¤¤Requirement = "¤Requirement";
	public static CharSequence ¤¤Requires = "¤Requires";
	public static CharSequence ¤¤Reset = "¤Reset";
	public static CharSequence ¤¤Resource = "¤Resource";
	public static CharSequence ¤¤Resources = "¤Resources";
	public static CharSequence ¤¤Reviews = "¤Reviews";
	public static CharSequence ¤¤Riches = "¤Riches";
	public static CharSequence ¤¤RightClick = "¤Right Click";
	public static CharSequence ¤¤SAVING = "¤SAVING";
	public static CharSequence ¤¤Search = "¤Search";
	public static CharSequence ¤¤Sell = "¤Sell";
	public static CharSequence ¤¤SendOutArmyToggleD = "¤When toggled, have soldiers leave for armies on the world map, even if they haven't reached their training target.";
	public static CharSequence ¤¤Sellers = "¤Sellers";
	public static CharSequence ¤¤Settings = "¤Settings";
	public static CharSequence ¤¤Settlement = "¤Settlement";
	public static CharSequence ¤¤Shape = "¤Shape";
	public static CharSequence ¤¤Showing = "¤Showing";
	public static CharSequence ¤¤Skill = "¤Skill";
	public static CharSequence ¤¤Sold = "¤Sold";
	public static CharSequence ¤¤Soldiers = "¤Soldiers";
	public static CharSequence ¤¤SoldiersTarget = "¤Soldiers Target";
	public static CharSequence ¤¤Sort = "¤Sort";
	public static CharSequence ¤¤Specification = "¤Specification";
	public static CharSequence ¤¤Speed = "¤Speed";
	public static CharSequence ¤¤Spoilage = "Decay";
	public static CharSequence ¤¤Spoils = "¤Spoils";
	public static CharSequence ¤¤Spread = "¤Spread";
	public static CharSequence ¤¤Start = "¤Start";
	public static CharSequence ¤¤Stop = "¤Stop";
	public static CharSequence ¤¤Storage = "¤Storage";
	public static CharSequence ¤¤Stored = "¤Stored";
	public static CharSequence ¤¤Structures = "¤Structures";
	public static CharSequence ¤¤Subject = "¤Subject";
	public static CharSequence ¤¤Subjects = "¤Subjects";
	public static CharSequence ¤¤SupportRoom = "¤Support";
	public static CharSequence ¤¤Supplies = "¤Supplies";
	public static CharSequence ¤¤SuppliesD = "¤Campaigning armies requires supplies to function. Some are essential, while others only provide morale boosts.";
	public static CharSequence ¤¤Target = "¤Target";
	public static CharSequence ¤¤Tariff = "¤Tariff";
	public static CharSequence ¤¤TariffD = "¤Tariff is applied to the amount of work that has been put into a resource and deducted from a faction's buy price. The tariff depends on your current stance. Overloading a faction with a particular resource also increases tariff.";
	public static CharSequence ¤¤Taxes = "¤Taxes";
	public static CharSequence ¤¤Threat = "¤Threat";
	public static CharSequence ¤¤TechnologyShort = "¤Tech";
	public static CharSequence ¤¤Terrain = "¤Terrain";
	public static CharSequence ¤¤Timer = "Timer";
	public static CharSequence ¤¤To = "To";
	public static CharSequence ¤¤Toll = "¤Toll";
	public static CharSequence ¤¤TollD = "Toll is based on the distance between you and this faction. The toll is added to the sell price and subtracted from the buy price.";
	public static CharSequence ¤¤Total = "¤Total";
	public static CharSequence ¤¤Tools = "¤Tools";
	public static CharSequence ¤¤TotalCost = "¤Total Cost";
	public static CharSequence ¤¤Tourist = "¤Tourist";
	public static CharSequence ¤¤Tourists = "¤Tourists";
	public static CharSequence ¤¤Trade = "¤Trade";
	public static CharSequence ¤¤Treasury = "¤Treasury";
	public static CharSequence ¤¤Trespassing = "¤Trespassing Armies.";
	public static CharSequence ¤¤TrespassingD = "¤Trespassing enemy armies in your realm.";
	public static CharSequence ¤¤Type = "Type";
	public static CharSequence ¤¤Unavailable = "¤Unavailable";
	public static CharSequence ¤¤Undo = "¤Undo";
	public static CharSequence ¤¤Unitinfo = "Click and drag a unit to rearrange it in the army. Hold {0} to select several units. Hold {1} and click to toggle units.";
	public static CharSequence ¤¤Unlocks = "¤Unlocks";
	public static CharSequence ¤¤Unreachable = "¤Unreachable";
	public static CharSequence ¤¤Upgrade = "¤Upgrade";
	public static CharSequence ¤¤Upkeep = "¤Upkeep";
	public static CharSequence ¤¤Used = "Used";
	public static CharSequence ¤¤Value = "Value";
	public static CharSequence ¤¤Victory = "Victory";
	public static CharSequence ¤¤War = "¤War";
	public static CharSequence ¤¤WarD = "¤This faction is at war with you, and will send its armies after you until a peace is brokered.";
	public static CharSequence ¤¤Water = "¤Water";
	public static CharSequence ¤¤Workforce = "¤Workforce";
	public static CharSequence ¤¤WorkVerb = "¤Work";
	public static CharSequence ¤¤WorkShift = "¤Work Shift";
	public static CharSequence ¤¤WorkforceD = "¤Your rooms require employees to function. These workers will stick to their place of work. Those not employed are named 'oddjobbers'. These will do other jobs, such as building and clearing.";

	public static CharSequence ¤¤World = "¤World";
	public static CharSequence ¤¤Yes = "¤Yes";
	public static CharSequence ¤¤and = "¤and";
	
	public static CharSequence ¤¤basePrice = "Base Price";
	public static CharSequence ¤¤buyPrice = "¤Buy Price";
	public static CharSequence ¤¤avePrice = "¤Average Price";
	public static CharSequence ¤¤cancel = "¤cancel";
	public static CharSequence ¤¤confirm = "¤confirm";
	public static CharSequence ¤¤construction = "Construction";
	public static CharSequence ¤¤delete = "¤delete";
	
	public static CharSequence ¤¤floor = "¤floor";
	public static CharSequence ¤¤garrison = "garrison";
	public static CharSequence ¤¤global = "global";
	public static CharSequence ¤¤goods = "Goods";
	public static CharSequence ¤¤ground = "ground";
	public static CharSequence ¤¤havens = "havens";
	public static CharSequence ¤¤limit = "¤limit";
	public static CharSequence ¤¤load = "¤load";
	public static CharSequence ¤¤loading = "¤loading...";
	public static CharSequence ¤¤name = "¤name";
	public static CharSequence ¤¤new = "¤new";
	public static CharSequence ¤¤newArrival = "¤New Arrival";
	public static CharSequence ¤¤noTrade = "¤There are no traders of this resource available.";
	public static CharSequence ¤¤noTradePartners = "¤You have no trade agreements for this resource. An agreement must be reached through diplomacy with a neighbouring faction";
	public static CharSequence ¤¤off = "¤off";
	public static CharSequence ¤¤on = "¤on";
	public static CharSequence ¤¤peace = "Peace Treaty";
	public static CharSequence ¤¤remove = "¤remove";
	public static CharSequence ¤¤rename = "¤rename";

	public static CharSequence ¤¤save = "¤save";
	public static CharSequence ¤¤sellPrice = "¤Sell Price";
	public static CharSequence ¤¤taxes = "¤Taxes";

	private static CharSequence ¤¤North = "North";
	private static CharSequence ¤¤NorthEast = "North-East";
	private static CharSequence ¤¤East = "East";
	private static CharSequence ¤¤SouthEast = "South-East";
	private static CharSequence ¤¤South = "South";
	private static CharSequence ¤¤SouthWest = "South-West";
	private static CharSequence ¤¤West = "West";
	private static CharSequence ¤¤NorthWest = "North-West";
	private static CharSequence ¤¤Central = "Central";
	
	public static CharSequence get(DIR d) {
		if (d == DIR.N)
			return ¤¤North;
		if (d == DIR.NE)
			return ¤¤NorthEast;
		if (d == DIR.E)
			return ¤¤East;
		if (d == DIR.SE)
			return ¤¤SouthEast;
		if (d == DIR.S)
			return ¤¤South;
		if (d == DIR.SW)
			return ¤¤SouthWest;
		if (d == DIR.W)
			return ¤¤West;
		if (d == DIR.NW)
			return ¤¤NorthWest;
		return ¤¤Central;
	}
	
	
	static {
		D.ts(Dic.class);
	}
	
}
